version: '2.1'
services: 
    redis:
        image: redis:5.0.1
        container_name: redis
        ports:
            - "6379:6379"

    mysql:
        image: mysql:5.7.24
        container_name: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"

    mq:
        image: rabbitmq:3.7.8-management
        container_name: rabbitmq
        ports:
            - "15672:15672"

    php-fpm:
        build: ./php
        container_name: phpfpm
        ports:
            - "9000:9000"
        depends_on:
            - mysql
            - redis
            - mq

    nginx:
        image: nginx:1.14.1
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - php-fpm

