# base image
FROM php:7.2-fpm

# MAINTAINER
MAINTAINER sucret@163.com

# put nginx-1.14.1.tar.gz into /usr/local/src and unpack nginx
# ADD nginx-1.14.1.tar.gz /usr/local/src

# running required command
RUN apt-get update 


# ENV PATH /usr/local/nginx/sbin:$PATH

# EXPOSE 80

# CMD /bin/sh -c 'nginx -g "daemon off;"'


